/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_onyxplatform_api_java_instance_NativeOnyxFn */

#ifndef _Included_org_onyxplatform_api_java_instance_NativeOnyxFn
#define _Included_org_onyxplatform_api_java_instance_NativeOnyxFn
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_onyxplatform_api_java_instance_NativeOnyxFn
 * Method:    initNative
 * Signature: (Ljava/lang/Object;Lclojure/lang/IPersistentMap;)Lclojure/lang/IPersistentMap;
 */
JNIEXPORT jobject JNICALL Java_org_onyxplatform_api_java_instance_NativeOnyxFn_initNative
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     org_onyxplatform_api_java_instance_NativeOnyxFn
 * Method:    releaseNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_onyxplatform_api_java_instance_NativeOnyxFn_releaseNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
