/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class onyxplatform_test_AssocFn */

#ifndef _Included_onyxplatform_test_AssocFn
#define _Included_onyxplatform_test_AssocFn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     onyxplatform_test_AssocFn
 * Method:    assocObj
 * Signature: (Lclojure/lang/IPersistentMap;Ljava/lang/String;Ljava/lang/Object;)Lclojure/lang/IPersistentMap;
 */
JNIEXPORT jobject JNICALL Java_onyxplatform_test_AssocFn_assocObj
  (JNIEnv *, jobject, jobject, jstring, jobject);

/*
 * Class:     onyxplatform_test_AssocFn
 * Method:    assocInt
 * Signature: (Lclojure/lang/IPersistentMap;Ljava/lang/String;I)Lclojure/lang/IPersistentMap;
 */
JNIEXPORT jobject JNICALL Java_onyxplatform_test_AssocFn_assocInt
  (JNIEnv *, jobject, jobject, jstring, jint);

/*
 * Class:     onyxplatform_test_AssocFn
 * Method:    assocFloat
 * Signature: (Lclojure/lang/IPersistentMap;Ljava/lang/String;F)Lclojure/lang/IPersistentMap;
 */
JNIEXPORT jobject JNICALL Java_onyxplatform_test_AssocFn_assocFloat
  (JNIEnv *, jobject, jobject, jstring, jfloat);

/*
 * Class:     onyxplatform_test_AssocFn
 * Method:    assocDouble
 * Signature: (Lclojure/lang/IPersistentMap;Ljava/lang/String;D)Lclojure/lang/IPersistentMap;
 */
JNIEXPORT jobject JNICALL Java_onyxplatform_test_AssocFn_assocDouble
  (JNIEnv *, jobject, jobject, jstring, jdouble);

/*
 * Class:     onyxplatform_test_AssocFn
 * Method:    assocBool
 * Signature: (Lclojure/lang/IPersistentMap;Ljava/lang/String;Z)Lclojure/lang/IPersistentMap;
 */
JNIEXPORT jobject JNICALL Java_onyxplatform_test_AssocFn_assocBool
  (JNIEnv *, jobject, jobject, jstring, jboolean);

/*
 * Class:     onyxplatform_test_AssocFn
 * Method:    assocStr
 * Signature: (Lclojure/lang/IPersistentMap;Ljava/lang/String;Ljava/lang/String;)Lclojure/lang/IPersistentMap;
 */
JNIEXPORT jobject JNICALL Java_onyxplatform_test_AssocFn_assocStr
  (JNIEnv *, jobject, jobject, jstring, jstring);

/*
 * Class:     onyxplatform_test_AssocFn
 * Method:    assocKeyword
 * Signature: (Lclojure/lang/IPersistentMap;Ljava/lang/String;Ljava/lang/Object;)Lclojure/lang/IPersistentMap;
 */
JNIEXPORT jobject JNICALL Java_onyxplatform_test_AssocFn_assocKeyword
  (JNIEnv *, jobject, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
