/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class onyxplatform_test_EmptyFn */

#ifndef _Included_onyxplatform_test_EmptyFn
#define _Included_onyxplatform_test_EmptyFn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     onyxplatform_test_EmptyFn
 * Method:    createEmptyMap
 * Signature: ()Lclojure/lang/IPersistentMap;
 */
JNIEXPORT jobject JNICALL Java_onyxplatform_test_EmptyFn_createEmptyMap
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
